language: go
go:
- 1.0
- 1.1
- 1.2
- 1.3
- tip
before_install: 
- export TRAVIS_GO_VERSION_INT=`echo $TRAVIS_GO_VERSION | sed 's/[^0-9]//g'`
install: 
- if [[ $TRAVIS_GO_VERSION_INT -gt 110 ]]; then make packages; fi
script: 
- if [[ $TRAVIS_GO_VERSION_INT -gt 110 ]]; then go test -v -covermode=count -coverprofile=./coverage.out && $HOME/gopath/bin/goveralls -coverprofile=./coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN; else go test -v; fi 
env:
  global:
    secure: j7Xv+JD6RtZgKaWPr+6LIdkBmBpL2bPf65oE5FUOh2Vzw59rHqGCXd+GO34RrLXNat0OJTmN1dGJPyt8PWI21qvxccvy39K7wD+aifmxvaPSp8aMnbkxts4Js4E3yy58/MIYLvi+N1yt95KzxQVImLc30zI32v4eCOTWjL0PrxM=
