language: go
go:
- 1.0
- 1.1
- 1.2
- 1.3
- tip
install: if [[ ${TRAVIS_GO_VERSION:0:5} != 'go1.0' && ${TRAVIS_GO_VERSION:0:5} != 'go1.1' ]]; then make packages; fi
script: if [[ ${TRAVIS_GO_VERSION:0:5} == 'go1.0' || ${TRAVIS_GO_VERSION:0:5} == 'go1.1' ]]; then go test -v; else go test -v -covermode=count -coverprofile=./coverage.out && $HOME/gopath/bin/goveralls -coverprofile=./coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN fi 
env:
  global:
    secure: j7Xv+JD6RtZgKaWPr+6LIdkBmBpL2bPf65oE5FUOh2Vzw59rHqGCXd+GO34RrLXNat0OJTmN1dGJPyt8PWI21qvxccvy39K7wD+aifmxvaPSp8aMnbkxts4Js4E3yy58/MIYLvi+N1yt95KzxQVImLc30zI32v4eCOTWjL0PrxM=
